defaults:
  - _self_
  - env: ???

embodiment_dataset_name: ??
demonstration_dataset_name: ??

algo_name: bco
seed: 42
log_name: "${env.name}/${environment_setup}/${embodiment_dataset_name}/${demonstration_dataset_name}/${num_exp