class: dmc
name: "${env.embodiment}-${env.task}"
embodiment: humanoid
task: stand
supported_tasks: [stand, walk, run]
action_repeat: 2
sensors:
  joint_angles:
    modility: tabular
    order: first
  head_height:
    modility: tabular 
    order: first
  extremitie